name: generate hydravim doc
on:
  repository_dispatch:
    types: [generate-doc]
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout current repository
      uses: actions/checkout@v3
      with:
        repository: HydraVim/HydraDoc
        path: HydraDoc
    - name: Checkout HydraVim repository
      uses: actions/checkout@v3
      with:
        repository: HydraVim/HydraVim
        path: HydraVim
    - name: Install ldoc
      run: sudo apt-get install lua-ldoc tree
    - name: Generate documentation
      run: |
        cp -f HydraDoc/config.ld HydraVim
        ldoc HydraVim/.
    - name: Push doc
      run: |
        cd HydraDoc
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git config user.name "github-actions[bot]"
        git remote set-url origin https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git
        git add .
        git diff --quiet && git diff --staged --quiet || (git commit -a -m "doc: update doc [action]"; git push origin HEAD:${GITHUB_REF})
